/**
 * @generated -- AUTO-GENERATED FILE -- DO NOT EDIT
 * Changes may be overwritten.
 *
 * Generated by: scripts/textures/generate.mts
 * Regenerate with: pnpm generate:textures
 */

import paperTexture0 from './paper-texture-0.svg?raw'
import paperTexture1 from './paper-texture-1.svg?raw'
import paperTexture2 from './paper-texture-2.svg?raw'
import paperTexture3 from './paper-texture-3.svg?raw'
import paperTexture4 from './paper-texture-4.svg?raw'

export const paperTextures = [paperTexture0, paperTexture1, paperTexture2, paperTexture3, paperTexture4]
