/**
 * @generated -- AUTO-GENERATED FILE -- DO NOT EDIT
 * Changes may be overwritten.
 *
 * Generated by: scripts/textures/generate.mts
 * Regenerate with: pnpm generate:textures
 */

export const paperVariantCount = 5
export const noiseVariantCount = 5
