/**
 * Regenerates the tiling textures under src/_shared/textures.
 *
 *   pnpm generate:textures                      both kinds, every variant
 *   pnpm generate:textures:paper                paper only
 *   pnpm generate:textures:noise                noise only
 *
 *   --count <n>     how many variants exist   (default: what's on disk, else 5)
 *   --variant <n>   regenerate only this one  (repeatable)
 *   --seed <n>      run seed                  (default: random — always printed)
 *   --dry-run       report the writes without making them
 *
 * Each variant draws from its own stream, so `--variant 3 --seed 1234` always
 * gives the same mesh no matter what else is regenerated alongside it. The seed
 * that produced a file is written into its header, so a variant you like can be
 * made again.
 *
 * Variant 0 of both kinds is a fixed preset — the hand-drawn original — and
 * ignores --seed. For the noise it is also the pre-boot CSS default, so the page
 * has its grain before any script runs. The paper has no such default: it is a
 * component, and a device without a variant gets a plain sheet.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'

import { createNoiseSeed, renderNoiseTexture } from './noise.mts'
import { createPaperMesh, originalPaperMesh, renderPaperTexture } from './paper.mts'
import { createRandom, variantSeed } from './random.mts'

type Kind = 'paper' | 'noise'

const kinds: Kind[] = ['paper', 'noise']
const defaultCount = 5
const texturesDir = fileURLToPath(new URL('../../src/_shared/textures/', import.meta.url))

const filePattern: Record<Kind, RegExp> = {
	paper: /^paper-texture-(\d+)\.svg$/,
	noise: /^page-noise-(\d+)\.svg$/,
}

function paperFile(variant: number) {
	return join(texturesDir, `paper-texture-${variant}.svg`)
}

function noiseFile(variant: number) {
	return join(texturesDir, `page-noise-${variant}.svg`)
}

/**
 * Highest variant index on disk, plus one — not a file count, so a gap left by
 * a deleted file doesn't silently renumber the variants after it.
 */
function countOnDisk(kind: Kind): number {
	if (!existsSync(texturesDir)) return 0
	let highest = -1
	for (const name of readdirSync(texturesDir)) {
		const match = filePattern[kind].exec(name)
		if (match) highest = Math.max(highest, Number(match[1]))
	}
	return highest + 1
}

function svgHeader(kind: Kind, variant: number, seed: number): string {
	// No "--" anywhere in here, which rules out spelling the flags out: XML
	// forbids "--" inside a comment, and an SVG that isn't well-formed is
	// rejected outright by the browser — the texture silently stops painting.
	// The variant and seed are what you need to make this file again;
	// docs/textures.md has the command they go on.
	const origin = variant === 0
		? 'the fixed original preset'
		: `${kind} variant ${variant}, seed ${seed}`
	return `<!-- @generated by scripts/textures/generate.mts. DO NOT EDIT. Source: ${origin}. -->`
}

const moduleHeader = [
	'/**',
	' * @generated -- AUTO-GENERATED FILE -- DO NOT EDIT',
	' * Changes may be overwritten.',
	' *',
	' * Generated by: scripts/textures/generate.mts',
	' * Regenerate with: pnpm generate:textures',
	' */',
].join('\n')

function renderCss(noiseCount: number): string {
	const lines = [
		moduleHeader,
		'',
		'/* The page grain only. The paper is a component (paper-texture.mts), because',
		'   its facets are themed with custom properties and an SVG behind url() can',
		'   never see them. The noise needs no such thing: it is translucent, so the',
		'   page colour below it does the theming.',
		'',
		'   The variant is set by _shared/services/texture-variant.mts; :root carries',
		'   variant 0 so the page has its grain before that module runs. */',
		':root {',
		'\t--texture-noise:      url("./page-noise-0.svg");',
		'}',
	]

	for (let variant = 1; variant < noiseCount; variant++) {
		lines.push(
			'',
			`:root[data-noise="${variant}"] {`,
			`\t--texture-noise:      url("./page-noise-${variant}.svg");`,
			'}',
		)
	}

	return `${lines.join('\n')}\n`
}

function renderModule(noiseCount: number): string {
	return [
		moduleHeader,
		'',
		`export const noiseVariantCount = ${noiseCount}`,
		'',
	].join('\n')
}

/**
 * The paper meshes, inlined rather than referenced: the facets are filled with
 * custom properties, which only resolve once the markup is part of the
 * document. The paper variant count is this array's length — one source of
 * truth rather than a number that can drift from the files on disk.
 */
function renderPaperModule(paperCount: number): string {
	const variants = Array.from({ length: paperCount }, (_, variant) => variant)
	return [
		moduleHeader,
		'',
		...variants.map((variant) =>
			`import paperTexture${variant} from './paper-texture-${variant}.svg?raw'`),
		'',
		`export const paperTextures = [${variants.map((v) => `paperTexture${v}`).join(', ')}]`,
		'',
	].join('\n')
}

const written: string[] = []
const unchanged: string[] = []

/**
 * An SVG is parsed as XML, so a comment containing "--" makes the whole file
 * unparseable and the browser paints nothing at all — with no error anywhere.
 * Cheap to check here, invisible until someone looks at the rendered page.
 */
function assertWellFormedSvg(path: string, markup: string): void {
	const comments = markup.match(/<!--[\s\S]*?-->/g) ?? []
	for (const comment of comments) {
		if (comment.slice(4, -3).includes('--')) {
			throw new Error(`${basename(path)}: XML comments cannot contain "--"\n  ${comment}`)
		}
	}
}

function writeIfChanged(path: string, content: string, dryRun: boolean): void {
	if (path.endsWith('.svg')) assertWellFormedSvg(path, content)

	const existing = existsSync(path) ? readFileSync(path, 'utf8') : undefined
	if (existing === content) {
		unchanged.push(basename(path))
		return
	}
	if (!dryRun) writeFileSync(path, content, 'utf8')
	written.push(basename(path))
}

function generatePaper(variant: number, seed: number, dryRun: boolean): void {
	const mesh = variant === 0
		? originalPaperMesh
		: createPaperMesh(createRandom(variantSeed(seed, 'paper', variant)))
	// One file per variant, whatever the theme: the facets are filled with
	// custom properties, so the ambient-light sensor flipping mid-game recolours
	// the paper without it rearranging itself.
	writeIfChanged(paperFile(variant), renderPaperTexture(mesh, svgHeader('paper', variant, seed)), dryRun)
}

function generateNoise(variant: number, seed: number, dryRun: boolean): void {
	const noiseSeed = variant === 0
		? 0
		: createNoiseSeed(createRandom(variantSeed(seed, 'noise', variant)))
	writeIfChanged(noiseFile(variant), renderNoiseTexture(noiseSeed, svgHeader('noise', variant, seed)), dryRun)
}

function parseInteger(value: string | undefined, name: string): number | undefined {
	if (value === undefined) return undefined
	const parsed = Number(value)
	if (!Number.isInteger(parsed) || parsed < 0) {
		throw new Error(`--${name} expects a non-negative integer, got "${value}"`)
	}
	return parsed
}

function main(): void {
	const { values } = parseArgs({
		options: {
			kind: { type: 'string' },
			count: { type: 'string' },
			variant: { type: 'string', multiple: true },
			seed: { type: 'string' },
			'dry-run': { type: 'boolean', default: false },
		},
	})

	if (values.kind !== undefined && !kinds.includes(values.kind as Kind)) {
		throw new Error(`--kind expects ${kinds.join(' or ')}, got "${values.kind}"`)
	}

	const selected = values.kind === undefined ? kinds : [values.kind as Kind]
	const dryRun = values['dry-run'] === true
	const seed = parseInteger(values.seed, 'seed') ?? Math.floor(Math.random() * 0xFFFFFFFF)
	const countArg = parseInteger(values.count, 'count')
	if (countArg === 0) throw new Error('--count must be at least 1')

	const counts: Record<Kind, number> = {
		paper: countOnDisk('paper') || defaultCount,
		noise: countOnDisk('noise') || defaultCount,
	}
	for (const kind of selected) {
		if (countArg !== undefined) counts[kind] = countArg
	}

	const requested = values.variant?.map((value) => parseInteger(value, 'variant')!)

	console.log(`seed ${seed}${dryRun ? ' (dry run)' : ''}`)

	for (const kind of selected) {
		const variants = requested ?? Array.from({ length: counts[kind] }, (_, index) => index)
		for (const variant of variants) {
			if (variant >= counts[kind]) {
				throw new Error(`--variant ${variant} is outside the ${counts[kind]} ${kind} variants`)
			}
			if (kind === 'paper') generatePaper(variant, seed, dryRun)
			else generateNoise(variant, seed, dryRun)
		}
	}

	writeIfChanged(join(texturesDir, 'textures.g.css'), renderCss(counts.noise), dryRun)
	writeIfChanged(join(texturesDir, 'textures.g.mts'), renderModule(counts.noise), dryRun)
	writeIfChanged(join(texturesDir, 'paper-textures.g.mts'), renderPaperModule(counts.paper), dryRun)

	console.log(`${written.length} written${written.length ? `: ${written.join(', ')}` : ''}`)
	if (unchanged.length) console.log(`${unchanged.length} unchanged`)

	// Files above the variant count are no longer referenced by the generated
	// CSS. Left in place rather than deleted — removing art is the user's call.
	const orphans = kinds.flatMap((kind) => readdirSync(texturesDir)
		.filter((name) => {
			const match = filePattern[kind].exec(name)
			return match !== null && Number(match[1]) >= counts[kind]
		}))

	if (orphans.length) {
		console.warn(`\nunreferenced, delete by hand if you meant to drop them:\n  ${orphans.join('\n  ')}`)
	}
}

main()
